# Generated by Django 5.0.7 on 2024-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roommate_images/'),
        ),
    ]
