# Generated by Django 5.0.7 on 2024-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0006_room_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
