# Generated by Django 5.0.7 on 2024-08-05 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0007_accessory_price_roommateprofile_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='image',
        ),
        migrations.CreateModel(
            name='AccessoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accessory_images/')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roomapp.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roomapp.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoommateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roommate_images/')),
                ('roommate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roomapp.roommateprofile')),
            ],
        ),
    ]
