# Generated by Django 5.0.7 on 2024-08-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0008_remove_accessory_image_remove_room_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roommateimage',
            name='roommate_profile',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roomapp.accessory')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roomapp.room')),
                ('roommate_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roomapp.roommateprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessoryImage',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
        migrations.DeleteModel(
            name='RoommateImage',
        ),
    ]
