# Generated by Django 5.0.7 on 2024-08-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0009_remove_roomimage_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=120, upload_to='room_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roommate_images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
