# Generated by Django 5.0.7 on 2024-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0011_remove_accessory_image_remove_room_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='roommate_profile',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/', verbose_name='Attachment'),
        ),
    ]
