# Generated by Django 5.0.7 on 2024-08-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0012_alter_attachment_options_remove_attachment_accessory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='roomapp.accessory'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='roomapp.room'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='roommate_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='roomapp.roommateprofile'),
        ),
    ]
