# Generated by Django 5.0.7 on 2024-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0013_alter_attachment_options_attachment_accessory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to='attachments/', verbose_name='Attachment'),
        ),
    ]
