# Generated by Django 5.0.7 on 2024-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0014_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/', verbose_name='Attachment'),
        ),
    ]
