# Generated by Django 5.0.7 on 2024-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0015_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adjusted_with_age_max',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='room',
            name='adjusted_with_age_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='bills_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='for_female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='free_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='length_of_stay_max',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='room',
            name='length_of_stay_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='move_on_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='num_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='Single', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='adjusted_with_age_max',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='adjusted_with_age_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='bills_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='free_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='music',
            field=models.CharField(choices=[('Occasionally', 'Occasionally'), ('Anytime', 'Anytime'), ('No', 'No')], default='Occasionally', max_length=20),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='occupation',
            field=models.CharField(choices=[("Don't mind", "Don't mind"), ('Professional', 'Professional'), ('Student', 'Student')], default="Don't mind", max_length=20),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='timing_of_room_engagement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
